---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banner
  namespace: openshift-gitops
spec:
  project: banner
  source:
    repoURL: git@github.com:redlabclub/openshift4-config.git
    targetRevision: HEAD
    path: conf-banner 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
