---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-lab1
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/redlabclub/openshift4-config
    path: conf-openshift-gitops
  destination:
    name: lab1
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
