---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth-htpass-lab1
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/redlabclub/openshift4-config
    path: conf-oauth/overlays/htpass
  destination:
    name: lab1
