apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
- target:
    group: console.openshift.io
    version: v1
    kind: ConsoleNotification
    name: banner
  path: color.yml
